BlockSp: BlockSp::util Namespace Reference
BlockSp::util Namespace Reference
blocksp_utility.hpp contains several utility functions for the BlockSp/blitz data structures.
Classes
struct tv_Hash
Hash for TinyVectors to be used as keys for an unordered map/set.
struct tv_Equal
Equal for TinyVectors to be used as keys for an unordered map/set.
Functions
int constexpr power (int base, int exp)
Power: base^exp, for compile time powers.
int factorial (int n)
n!
int choose (int n, int k)
n choose k.
template<typename T>
T sqrt (T x)
Square root of x.
template<typename T>
T sqr (T x)
Square of x.
template<typename T>
T mag (T x)
Euclidean/L2 norm of x.
template<typename T>
T magsqr (T x)
Squared L2 norm of x.
template<typename T, int N>
T tvMax (const blitz::TinyVector< T, N > &tv)
Max of a TinyVector.
template<typename T, int N>
T tvMin (const blitz::TinyVector< T, N > &tv)
Min of a TinyVector.
template<typename T, int N>
T tvMaxAbs (const blitz::TinyVector< T, N > &tv)
Max absolute value of a TinyVector.
template<typename T, int N>
T tvMinAbs (const blitz::TinyVector< T, N > &tv)
Min absolute value of a TinyVector.
template<typename T, int N>
int tvArgMax (const blitz::TinyVector< T, N > &tv)
arg_max of a TinyVector.
template<typename T, int N>
int tvArgMin (const blitz::TinyVector< T, N > &tv)
arg_min of a TinyVector.
template<typename T, int N>
T tvMag (const blitz::TinyVector< T, N > &x)
Euclidean/L2 norm of a TinyVector.
template<typename T, int N>
T tvMagSqr (const blitz::TinyVector< T, N > &x)
Squared L2 norm of a TinyVector.
template<typename T, int N>
blitz::TinyVector< T, N > tvAbs (const blitz::TinyVector< T, N > &x)
Absolute value of each component of a TinyVector.
template<typename T, int N>
blitz::TinyVector< int, N > tvFloor (const blitz::TinyVector< ScalarType_t< T >, N > &tv)
Floor of each dimension of a TinyVector.
template<typename T, int N>
blitz::TinyVector< T, N > tvRev (const blitz::TinyVector< T, N > &tv)
Reverse a TinyVector.
template<typename T, typename S, int N>
blitz::TinyVector< T, N > tvPow (const blitz::TinyVector< T, N > &x, const blitz::TinyVector< S, N > &exp)
Raise a TinyVector to the power exp (each component seperately), ex: (x,y)^(a,b) = (x^a, y^b).
template<typename T, typename S, int N>
blitz::TinyVector< T, N > tvPow (const blitz::TinyVector< T, N > &x, S exp)
Raise a TinyVector to the power exp, ex: (x,y)^a = (x^a, y^a).
template<typename T, int B, int D>
blitz::TinyVector< T, B > tvSubset (const blitz::TinyVector< T, B *D > &tv, int dim)
Get a subset TinyVector of length B from a TinyVector of length B*D.
template<typename T, int B, int D>
blitz::TinyVector< T, B *D > tvConcat (const blitz::TinyVector< blitz::TinyVector< T, B >, D > &tv)
Concatenate a TinyVector<TinyVector> into a single TinyVector.
template<typename T, int N>
blitz::TinyVector< T, N - 1 > tvM1 (const blitz::TinyVector< T, N > &tv)
Subtract off the last dimension of a TinyVector.
template<typename T, int N>
T bdot (const blitz::TinyVector< T, N > &x, const blitz::TinyVector< T, N > &y)
blitz dot product of two TinyVectors, with complex conjugate.
template<typename T>
T bdot (const blitz::Array< T, 1 > &x, const blitz::Array< T, 1 > &y)
blitz dot product of two 1D blitz::Arrays, with complex conjugate.
template<typename T, int M, int N>
blitz::TinyVector< T, N > tmRow (const blitz::TinyMatrix< T, M, N > tm, int row)
Row of TinyMatrix.
template<typename T, int M, int N>
blitz::TinyVector< T, M > tmCol (const blitz::TinyMatrix< T, M, N > tm, int col)
Column of TinyMatrix.
template<typename T, int M, int N>
ScalarType_t< T > tmMaxAbs (const blitz::TinyMatrix< T, M, N > &A)
Max absolution value of a TinyMatrix.
template<typename T, int M, int N>
ScalarType_t< T > frobeniusNorm (const blitz::TinyMatrix< T, M, N > &A)
Frobenius norm of a TinyMatrix.
template<typename T, int M, int N>
ScalarType_t< T > oneNorm (const blitz::TinyMatrix< T, M, N > &A)
One norm of a TinyMatrix.
template<typename T, int M, int N>
ScalarType_t< T > infNorm (const blitz::TinyMatrix< T, M, N > &A)
Infinity norm of a TinyMatrix.
template<typename T, int B>
T trace (const blitz::TinyMatrix< T, B, B > &A)
Trace of a square TinyMatrix.
template<typename T, int N>
blitz::TinyMatrix< T, N, N > tangentMat (const blitz::TinyVector< T, N > &n)
Tangential matrix to normal vector n: I - n kron n.
template<typename T, int B>
T trace (const BlockSp< T, B > &A)
Trace of a BlockSp matrix.
template<typename T, int B>
ScalarType_t< T > frobeniusNorm (const BlockSp< T, B > &A)
Frobenius norm of BlockSp = trace(A^* A).
template<typename T, int N>
T determinant (const blitz::TinyMatrix< T, N, N > &A)
Calculate the determinant of a TinyMatrix.
template<typename T, int B, int D = 1>
solArray< T, B, D > rand_solArray (int l, bool normalized=true, ScalarType_t< T > min=0.0, ScalarType_t< T > max=1.0)
Return a randomly filled solArray.
template<typename T, int B>
BlockSp< T, B > rand_BlockSp (int m, int n, int nCol=4, ScalarType_t< T > min=0.0, ScalarType_t< T > max=1.0)
Generate a random mxn BlockSp matrix with ~ncol columns per row.
template<typename T>
std::vector< T > rand_vec (int l, bool normalized=true, ScalarType_t< T > min=0.0, ScalarType_t< T > max=1.0)
Return a randomly filled std::vector.
template<int N>
blitz::TinyVector< int, N > getStride (const blitz::TinyVector< int, N > &extent)
Get vector of strides from extent of an N-D blitz::Array.
template<int N>
int convIndexNto1 (const blitz::TinyVector< int, N > &indexND, const blitz::TinyVector< int, N > &stride)
Convert an N-D index to 1D index given a stride vector.
template<int N>
blitz::TinyVector< int, N > convIndex1toN (int index1D, const blitz::TinyVector< int, N > &extent)
Convert 1D index to N-D index given vector of extents.
template<typename T>
std::vector< T > extractSubVec (const std::vector< T > v, int start, int end)
Extract a subset of a std::vector.
template<typename T, int B, int D>
blitz::Array< T, 2 > getBlock (const blitz::Array< T, 2 > &arr, int i, int j)
Get a reference to a MxM block of a D*MxD*M 2D blitz::Array.
template<typename T, int B, int D>
blitz::Array< T, 1 > getBlock (const blitz::Array< T, 1 > &arr, int i)
Get a reference to a M vec of a D*M length 1D blitz::Array.
template<typename T, int B, int D>
void setBlock (blitz::TinyMatrix< T, B *D, B *D > &big, const blitz::TinyMatrix< T, B, B > &small, int i, int j)
Set an BxB block of BDxBD TinyMatrix from an BxB TinyMatrix, at location/block index (i,j).
template<typename T, int B>
void setFromGlobal (BlockSp< T, B > &A, int i, int j, T val)
Insert a value into a BlockSp matrix from a global index (i, j).
template<typename T, int B, int D = 1>
void setFromGlobal (solArray< T, B, D > &x, int i, T val)
Insert a value into a solArray from a global index i.
template<typename T, int B>
blitz::Array< T, 2 > blkToFull (const BlockSp< T, B > &blk)
Convert a BlockSp matrix to a full dense matrix.
template<typename T, int B, int D>
blitz::Array< T, 1 > saToFull (const solArray< T, B, D > &sa)
Convert a solArray to a full length 1D blitz::Array.
template<typename T, int B, int D>
std::vector< T > saToFull_vec (const solArray< T, B, D > &sa)
Convert a solArray to a full length std::vector.
template<typename T, int B, int D = 1>
solArray< T, B, D > fullToSA (const blitz::Array< T, 1 > &full, int numEls)
Convert a full length 1D blitz::Array to a solArray.
template<typename T, int B, int D = 1>
solArray< T, B, D > fullToSA (const std::vector< T > &full, int numEls)
Convert a full length std::vector to a solArray.
template<typename T, int M, int N>
blitz::Array< T, 2 > tnyMatToArr (const blitz::TinyMatrix< T, M, N > &mat)
Convert a TinyMatrix to a 2D array (which has better cout<< readability).
template<typename T, int M, int N>
blitz::TinyMatrix< T, M, N > arrToTnyMat (const blitz::Array< T, 2 > &arr)
Convert a 2D blitz::Array of size MxN to a TinyMatrix.
template<typename T, int B>
BlockSp< ComplexType_t< T >, B > makeComplex (const BlockSp< T, B > &A)
Make a complex BlockSp matrix from a scalar BlockSp matrix.
template<typename T, int B, int D = 1>
solArray< ComplexType_t< T >, B, D > makeComplex (const solArray< T, B, D > &x)
Make a complex solArray from a scalar solArray.
template<typename T, typename Compare>
std::vector< int > sort_permutation (const std::vector< T > &v, Compare compare)
Get a permutation vector from another vector and it's comparison function.
template<typename T, typename Compare>
std::vector< int > sort_permutation (const blitz::Array< T, 1 > &v, Compare compare)
template<typename T>
std::vector< T > apply_permutation (const std::vector< T > &v, const std::vector< int > &p)
Apply the permutation vector to another vector.
template<typename T>
blitz::Array< T, 1 > apply_permutation (const blitz::Array< T, 1 > &v, const std::vector< int > &p)
template<typename T>
void printV (const std::vector< T > &v)
Print std::vector.
template<typename T, int N>
blitz::TinyMatrix< T, N, N > explicit_small_Inv (const blitz::TinyMatrix< T, N, N > &A)
Compute explicit inverse of a small 1x1, 2x2, and 3x3 matrix A^-1 = 1/det * adj(A) det = deteminant of A, adj(A) = Adjoint matrix of A.
template<typename T, int N>
blitz::TinyMatrix< T, N, N > explicit_small_Inv (const blitz::TinyVector< T,(N *(N+1))/2 > &A)
Compute explicit inverse of a small symmetic matrix A stored in compact vector form.
template<class T>
void tv_hash_combine (std::size_t &seed, const T &v)
std::pair hash (from boost, for TinyVectors).
Detailed Description
blocksp_utility.hpp contains several utility functions for the BlockSp/blitz data structures.
These include:
1) Basic arithmetic, timers, random number functions.
2) TinyVector/Matrix operations, array/matrix manipulations.
3) Random BlockSp matrices and solArrays.
4) BlockSp to full dense matrix, solArray to full dense vector, and reverse.
5) Scalar to Complex BlockSp/solArray converters.
5) Explicit matrix inverse calculator for very small matrices.
6) Hash function for TinyVectors.
Function Documentation
apply_permutation() [1/2]
template<typename T> blitz::Array< T, 1 > BlockSp::util::apply_permutation (const blitz::Array< T, 1 > & v, const std::vector< int > & p)
Definition at line 817 of file blocksp_utility.hpp.
apply_permutation() [2/2]
template<typename T> std::vector< T > BlockSp::util::apply_permutation (const std::vector< T > & v, const std::vector< int > & p)
Apply the permutation vector to another vector.
Definition at line 809 of file blocksp_utility.hpp.
arrToTnyMat()
template<typename T, int M, int N> blitz::TinyMatrix< T, M, N > BlockSp::util::arrToTnyMat (const blitz::Array< T, 2 > & arr) inline
Convert a 2D blitz::Array of size MxN to a TinyMatrix.
Definition at line 736 of file blocksp_utility.hpp.
bdot() [1/2]
template<typename T> T BlockSp::util::bdot (const blitz::Array< T, 1 > & x, const blitz::Array< T, 1 > & y) inline
blitz dot product of two 1D blitz::Arrays, with complex conjugate.
Definition at line 287 of file blocksp_utility.hpp.
bdot() [2/2]
template<typename T, int N> T BlockSp::util::bdot (const blitz::TinyVector< T, N > & x, const blitz::TinyVector< T, N > & y) inline
blitz dot product of two TinyVectors, with complex conjugate.
Definition at line 277 of file blocksp_utility.hpp.
blkToFull()
template<typename T, int B> blitz::Array< T, 2 > BlockSp::util::blkToFull (const BlockSp< T, B > & blk) inline
Convert a BlockSp matrix to a full dense matrix.
Resulting matrix may be intractably large.
Definition at line 648 of file blocksp_utility.hpp.
choose()
int BlockSp::util::choose (int n, int k) inline
n choose k.
Definition at line 56 of file blocksp_utility.hpp.
References factorial().
convIndex1toN()
template<int N> blitz::TinyVector< int, N > BlockSp::util::convIndex1toN (int index1D, const blitz::TinyVector< int, N > & extent) inline
Convert 1D index to N-D index given vector of extents.
Definition at line 556 of file blocksp_utility.hpp.
convIndexNto1()
template<int N> int BlockSp::util::convIndexNto1 (const blitz::TinyVector< int, N > & indexND, const blitz::TinyVector< int, N > & stride) inline
Convert an N-D index to 1D index given a stride vector.
Definition at line 547 of file blocksp_utility.hpp.
determinant()
template<typename T, int N> T BlockSp::util::determinant (const blitz::TinyMatrix< T, N, N > & A)
Calculate the determinant of a TinyMatrix.
Warning! Explicit determinant calculations are an O(N!), where ! is factorial. Use for small N only.
Definition at line 394 of file blocksp_utility.hpp.
explicit_small_Inv() [1/2]
template<typename T, int N> blitz::TinyMatrix< T, N, N > BlockSp::util::explicit_small_Inv (const blitz::TinyMatrix< T, N, N > & A)
Compute explicit inverse of a small 1x1, 2x2, and 3x3 matrix A^-1 = 1/det * adj(A) det = deteminant of A, adj(A) = Adjoint matrix of A.
Definition at line 842 of file blocksp_utility.hpp.
explicit_small_Inv() [2/2]
template<typename T, int N> blitz::TinyMatrix< T, N, N > BlockSp::util::explicit_small_Inv (const blitz::TinyVector< T,(N *(N+1))/2 > & A)
Compute explicit inverse of a small symmetic matrix A stored in compact vector form.
A length N*(N+1)/2, stored as if spanning the LOWER triangular portion of a matrix. A^-1 = 1/det * adj(A) det = deteminant of A, adj(A) = Adjoint matrix of A. For N = 1, 2, and 3 only.
Definition at line 898 of file blocksp_utility.hpp.
extractSubVec()
template<typename T> std::vector< T > BlockSp::util::extractSubVec (const std::vector< T > v, int start, int end) inline
Extract a subset of a std::vector.
Definition at line 569 of file blocksp_utility.hpp.
factorial()
int BlockSp::util::factorial (int n) inline
n!
Definition at line 46 of file blocksp_utility.hpp.
Referenced by choose().
frobeniusNorm() [1/2]
template<typename T, int M, int N> ScalarType_t< T > BlockSp::util::frobeniusNorm (const blitz::TinyMatrix< T, M, N > & A) inline
Frobenius norm of a TinyMatrix.
Definition at line 330 of file blocksp_utility.hpp.
frobeniusNorm() [2/2]
template<typename T, int B> ScalarType_t< T > BlockSp::util::frobeniusNorm (const BlockSp< T, B > & A) inline
Frobenius norm of BlockSp = trace(A^* A).
Definition at line 384 of file blocksp_utility.hpp.
fullToSA() [1/2]
template<typename T, int B, int D = 1> solArray< T, B, D > BlockSp::util::fullToSA (const blitz::Array< T, 1 > & full, int numEls) inline
Convert a full length 1D blitz::Array to a solArray.
Assume full layout is as given from saToFull. el0(dim0 ... dimD) ... eln(dim0 ... dimD)
Definition at line 695 of file blocksp_utility.hpp.
fullToSA() [2/2]
template<typename T, int B, int D = 1> solArray< T, B, D > BlockSp::util::fullToSA (const std::vector< T > & full, int numEls) inline
Convert a full length std::vector to a solArray.
Assume full layout is as given from saToFull_vec. el0(dim0 ... dimD) ... eln(dim0 ... dimD)
Definition at line 712 of file blocksp_utility.hpp.
getBlock() [1/2]
template<typename T, int B, int D> blitz::Array< T, 1 > BlockSp::util::getBlock (const blitz::Array< T, 1 > & arr, int i) inline
Get a reference to a M vec of a D*M length 1D blitz::Array.
Definition at line 592 of file blocksp_utility.hpp.
getBlock() [2/2]
template<typename T, int B, int D> blitz::Array< T, 2 > BlockSp::util::getBlock (const blitz::Array< T, 2 > & arr, int i, int j) inline
Get a reference to a MxM block of a D*MxD*M 2D blitz::Array.
Note: the block references the input blitz::Array, changing the block changes the array.
Definition at line 580 of file blocksp_utility.hpp.
getStride()
template<int N> blitz::TinyVector< int, N > BlockSp::util::getStride (const blitz::TinyVector< int, N > & extent) inline
Get vector of strides from extent of an N-D blitz::Array.
Row major is assumed: so a 2x2x2 array has stride (4,2,1).
Definition at line 533 of file blocksp_utility.hpp.
infNorm()
template<typename T, int M, int N> ScalarType_t< T > BlockSp::util::infNorm (const blitz::TinyMatrix< T, M, N > & A) inline
Infinity norm of a TinyMatrix.
Definition at line 344 of file blocksp_utility.hpp.
mag()
template<typename T> T BlockSp::util::mag (T x) inline
Euclidean/L2 norm of x.
Definition at line 77 of file blocksp_utility.hpp.
magsqr()
template<typename T> T BlockSp::util::magsqr (T x) inline
Squared L2 norm of x.
Definition at line 84 of file blocksp_utility.hpp.
makeComplex() [1/2]
template<typename T, int B> BlockSp< ComplexType_t< T >, B > BlockSp::util::makeComplex (const BlockSp< T, B > & A)
Make a complex BlockSp matrix from a scalar BlockSp matrix.
If input matrix is already complex, that matrix is returned.
Definition at line 753 of file blocksp_utility.hpp.
makeComplex() [2/2]
template<typename T, int B, int D = 1> solArray< ComplexType_t< T >, B, D > BlockSp::util::makeComplex (const solArray< T, B, D > & x)
Make a complex solArray from a scalar solArray.
If input is already complex, that array is returned.
Definition at line 769 of file blocksp_utility.hpp.
oneNorm()
template<typename T, int M, int N> ScalarType_t< T > BlockSp::util::oneNorm (const blitz::TinyMatrix< T, M, N > & A) inline
One norm of a TinyMatrix.
Definition at line 337 of file blocksp_utility.hpp.
power()
int constexpr BlockSp::util::power (int base, int exp) inline constexpr
Power: base^exp, for compile time powers.
Definition at line 40 of file blocksp_utility.hpp.
References power().
Referenced by power().
printV()
template<typename T> void BlockSp::util::printV (const std::vector< T > & v) inline
Print std::vector.
Definition at line 827 of file blocksp_utility.hpp.
rand_BlockSp()
template<typename T, int B> BlockSp< T, B > BlockSp::util::rand_BlockSp (int m, int n, int nCol = 4, ScalarType_t< T > min = 0.0, ScalarType_t< T > max = 1.0)
Generate a random mxn BlockSp matrix with ~ncol columns per row.
Random numbers from min to max
Definition at line 464 of file blocksp_utility.hpp.
rand_solArray()
template<typename T, int B, int D = 1> solArray< T, B, D > BlockSp::util::rand_solArray (int l, bool normalized = true, ScalarType_t< T > min = 0.0, ScalarType_t< T > max = 1.0)
Return a randomly filled solArray.
If normalized, L2 norm = 1, random numbers from min to max.
Definition at line 439 of file blocksp_utility.hpp.
rand_vec()
template<typename T> std::vector< T > BlockSp::util::rand_vec (int l, bool normalized = true, ScalarType_t< T > min = 0.0, ScalarType_t< T > max = 1.0)
Return a randomly filled std::vector.
If normalized, L2 norm = 1. Random numbers from min to max.
Definition at line 495 of file blocksp_utility.hpp.
saToFull()
template<typename T, int B, int D> blitz::Array< T, 1 > BlockSp::util::saToFull (const solArray< T, B, D > & sa) inline
Convert a solArray to a full length 1D blitz::Array.
Definition at line 664 of file blocksp_utility.hpp.
saToFull_vec()
template<typename T, int B, int D> std::vector< T > BlockSp::util::saToFull_vec (const solArray< T, B, D > & sa) inline
Convert a solArray to a full length std::vector.
Definition at line 678 of file blocksp_utility.hpp.
setBlock()
template<typename T, int B, int D> void BlockSp::util::setBlock (blitz::TinyMatrix< T, B *D, B *D > & big, const blitz::TinyMatrix< T, B, B > & small, int i, int j) inline
Set an BxB block of BDxBD TinyMatrix from an BxB TinyMatrix, at location/block index (i,j).
Definition at line 602 of file blocksp_utility.hpp.
setFromGlobal() [1/2]
template<typename T, int B> void BlockSp::util::setFromGlobal (BlockSp< T, B > & A, int i, int j, T val)
Insert a value into a BlockSp matrix from a global index (i, j).
Note: this is not recommendeded and it is better practice to make Blocks/TinyMatrices locally on the stack, then allocate them to the BlockSp matrix.
Definition at line 615 of file blocksp_utility.hpp.
setFromGlobal() [2/2]
template<typename T, int B, int D = 1> void BlockSp::util::setFromGlobal (solArray< T, B, D > & x, int i, T val)
Insert a value into a solArray from a global index i.
Note: this is not recommendeded and it is better practice to make TinyVectors locally on the stack, then allocate them to the solArray.
Definition at line 630 of file blocksp_utility.hpp.
sort_permutation() [1/2]
template<typename T, typename Compare> std::vector< int > BlockSp::util::sort_permutation (const blitz::Array< T, 1 > & v, Compare compare)
Definition at line 798 of file blocksp_utility.hpp.
sort_permutation() [2/2]
template<typename T, typename Compare> std::vector< int > BlockSp::util::sort_permutation (const std::vector< T > & v, Compare compare)
Get a permutation vector from another vector and it's comparison function.
Definition at line 789 of file blocksp_utility.hpp.
sqr()
template<typename T> T BlockSp::util::sqr (T x) inline
Square of x.
Definition at line 70 of file blocksp_utility.hpp.
sqrt()
template<typename T> T BlockSp::util::sqrt (T x) inline
Square root of x.
Definition at line 63 of file blocksp_utility.hpp.
tangentMat()
template<typename T, int N> blitz::TinyMatrix< T, N, N > BlockSp::util::tangentMat (const blitz::TinyVector< T, N > & n)
Tangential matrix to normal vector n: I - n kron n.
Definition at line 360 of file blocksp_utility.hpp.
tmCol()
template<typename T, int M, int N> blitz::TinyVector< T, M > BlockSp::util::tmCol (const blitz::TinyMatrix< T, M, N > tm, int col) inline
Column of TinyMatrix.
Definition at line 313 of file blocksp_utility.hpp.
tmMaxAbs()
template<typename T, int M, int N> ScalarType_t< T > BlockSp::util::tmMaxAbs (const blitz::TinyMatrix< T, M, N > & A) inline
Max absolution value of a TinyMatrix.
Definition at line 323 of file blocksp_utility.hpp.
tmRow()
template<typename T, int M, int N> blitz::TinyVector< T, N > BlockSp::util::tmRow (const blitz::TinyMatrix< T, M, N > tm, int row) inline
Row of TinyMatrix.
Definition at line 303 of file blocksp_utility.hpp.
tnyMatToArr()
template<typename T, int M, int N> blitz::Array< T, 2 > BlockSp::util::tnyMatToArr (const blitz::TinyMatrix< T, M, N > & mat) inline
Convert a TinyMatrix to a 2D array (which has better cout<< readability).
Definition at line 727 of file blocksp_utility.hpp.
trace() [1/2]
template<typename T, int B> T BlockSp::util::trace (const blitz::TinyMatrix< T, B, B > & A) inline
Trace of a square TinyMatrix.
Definition at line 351 of file blocksp_utility.hpp.
trace() [2/2]
template<typename T, int B> T BlockSp::util::trace (const BlockSp< T, B > & A) inline
Trace of a BlockSp matrix.
Definition at line 372 of file blocksp_utility.hpp.
tv_hash_combine()
template<class T> void BlockSp::util::tv_hash_combine (std::size_t & seed, const T & v) inline
std::pair hash (from boost, for TinyVectors).
Definition at line 952 of file blocksp_utility.hpp.
tvAbs()
template<typename T, int N> blitz::TinyVector< T, N > BlockSp::util::tvAbs (const blitz::TinyVector< T, N > & x) inline
Absolute value of each component of a TinyVector.
Definition at line 190 of file blocksp_utility.hpp.
tvArgMax()
template<typename T, int N> int BlockSp::util::tvArgMax (const blitz::TinyVector< T, N > & tv) inline
arg_max of a TinyVector.
Definition at line 136 of file blocksp_utility.hpp.
tvArgMin()
template<typename T, int N> int BlockSp::util::tvArgMin (const blitz::TinyVector< T, N > & tv) inline
arg_min of a TinyVector.
Definition at line 153 of file blocksp_utility.hpp.
tvConcat()
template<typename T, int B, int D> blitz::TinyVector< T, B *D > BlockSp::util::tvConcat (const blitz::TinyVector< blitz::TinyVector< T, B >, D > & tv) inline
Concatenate a TinyVector<TinyVector> into a single TinyVector.
Definition at line 258 of file blocksp_utility.hpp.
tvFloor()
template<typename T, int N> blitz::TinyVector< int, N > BlockSp::util::tvFloor (const blitz::TinyVector< ScalarType_t< T >, N > & tv) inline
Floor of each dimension of a TinyVector.
Definition at line 197 of file blocksp_utility.hpp.
tvM1()
template<typename T, int N> blitz::TinyVector< T, N - 1 > BlockSp::util::tvM1 (const blitz::TinyVector< T, N > & tv) inline
Subtract off the last dimension of a TinyVector.
Definition at line 269 of file blocksp_utility.hpp.
tvMag()
template<typename T, int N> T BlockSp::util::tvMag (const blitz::TinyVector< T, N > & x) inline
Euclidean/L2 norm of a TinyVector.
Definition at line 170 of file blocksp_utility.hpp.
tvMagSqr()
template<typename T, int N> T BlockSp::util::tvMagSqr (const blitz::TinyVector< T, N > & x) inline
Squared L2 norm of a TinyVector.
Definition at line 180 of file blocksp_utility.hpp.
tvMax()
template<typename T, int N> T BlockSp::util::tvMax (const blitz::TinyVector< T, N > & tv) inline
Max of a TinyVector.
Definition at line 96 of file blocksp_utility.hpp.
tvMaxAbs()
template<typename T, int N> T BlockSp::util::tvMaxAbs (const blitz::TinyVector< T, N > & tv) inline
Max absolute value of a TinyVector.
Definition at line 116 of file blocksp_utility.hpp.
tvMin()
template<typename T, int N> T BlockSp::util::tvMin (const blitz::TinyVector< T, N > & tv) inline
Min of a TinyVector.
Definition at line 106 of file blocksp_utility.hpp.
tvMinAbs()
template<typename T, int N> T BlockSp::util::tvMinAbs (const blitz::TinyVector< T, N > & tv) inline
Min absolute value of a TinyVector.
Definition at line 126 of file blocksp_utility.hpp.
tvPow() [1/2]
template<typename T, typename S, int N> blitz::TinyVector< T, N > BlockSp::util::tvPow (const blitz::TinyVector< T, N > & x, const blitz::TinyVector< S, N > & exp) inline
Raise a TinyVector to the power exp (each component seperately), ex: (x,y)^(a,b) = (x^a, y^b).
Definition at line 221 of file blocksp_utility.hpp.
tvPow() [2/2]
template<typename T, typename S, int N> blitz::TinyVector< T, N > BlockSp::util::tvPow (const blitz::TinyVector< T, N > & x, S exp) inline
Raise a TinyVector to the power exp, ex: (x,y)^a = (x^a, y^a).
Definition at line 233 of file blocksp_utility.hpp.
tvRev()
template<typename T, int N> blitz::TinyVector< T, N > BlockSp::util::tvRev (const blitz::TinyVector< T, N > & tv) inline
Reverse a TinyVector.
Definition at line 210 of file blocksp_utility.hpp.
tvSubset()
template<typename T, int B, int D> blitz::TinyVector< T, B > BlockSp::util::tvSubset (const blitz::TinyVector< T, B *D > & tv, int dim) inline
Get a subset TinyVector of length B from a TinyVector of length B*D.
Definition at line 243 of file blocksp_utility.hpp.