#BlockSp _config.yml

title: BlockSp
email: lpcorcos@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A templated C++ library for block sparse linear algebra.
baseurl: "" # the subpath of your site, e.g. /blog
url: "BlockSp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  BlockSp

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-redirect-from


